name: common_knowledge
description: Online school by Lev Klykov

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core:
  cloud_firestore: ^0.13.4
  firebase_auth: ^0.15.5
  firebase_auth_web: ^0.1.2
  google_sign_in: ^4.1.4
  provider: ^4.0.4
  curved_navigation_bar: ^0.3.2
  intl: ^0.16.1
  auto_size_text: ^2.1.0
  modal_progress_hud: ^0.1.3
  flutter_spinkit: ^4.1.2
  google_fonts: ^0.3.9
  datetime_picker_formfield: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
     - family: Drevnerusskij
       fonts:
         - asset: assets/fonts/Drevnerusskij.ttf
